# Generated by Django 3.1.1 on 2020-09-10 23:14

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200908_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.ManyToManyField(related_name='get_posts', to='blog.Category', verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=ckeditor.fields.RichTextField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de publicação'),
        ),
    ]
